export enum EnumScopes {
  USER = 'DEVSEEDER/PLACES/API/USER',
  ADM = 'DEVSEEDER/PLACES/API/ADM',
  GET_ALL = 'DEVSEEDER/PLACES/API/GET_ALL',
  UPDATE_PASSWORD = 'DEVSEEDER/PLACES/API/UPDATE_PASSWORD'
}

export const SCOPE_KEY = 'DEVSEEDER/PLACES/API';
